const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",

  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",

  //user
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",

  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",

  // Admin

  // Gender
  FETCH_GENDER_START: "FETCH_GENDER_START",
  FETCH_GENDER_SUCCESS: "FETCH GENDER SUCCESS",
  FETCH_GENDER_FAILED: "FETCH GENDER FAIL",

  // Position
  FETCH_POSITION_START: "FETCH_POSITION_START",
  FETCH_POSITION_SUCCESS: "FETCH POSITION SUCCESS",
  FETCH_POSITION_FAILED: "FETCH GENDER FAIL",

  // ROLE
  FETCH_ROLE_START: "FETCH_ROLE_START",
  FETCH_ROLE_SUCCESS: "FETCH_ROLE_SUCCESS",
  FETCH_ROLE_FAILED: "FETCH_ROLE_FAIL",

  CREATE_NEW_USER_SUCCESS: "CREATE_NEW_USER_SUCCESS",
  CREATE_NEW_USER_FAILED: "CREATE_NEW_USER_FAILED",

  FETCH_ALL_USER_SUCCESS: "FETCH_ALL_USER_SUCCESS",
  FETCH_ALL_USER_FAILED: "FETCH_ALL_USER_FAIL",

  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAILED: "DELETE_USER_FAIL",

  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  UPDATE_USER_FAILED: "UPDATE_USER_FAIL",

  GET_TOP_DOCTOR_SUCCESS: "GET_TOP_DOCTOR_SUCCESS",
  GET_TOP_DOCTOR_FAILED: "GET_TOP_DOCTOR_FAIL",

  GET_ALL_DOCTORS_SUCCESS: "GET_ALL_DOCTORS_SUCCESS",
  GET_ALL_DOCTORS_FAILED: "GET_ALL_DOCTORS_FAIL",

  CREATE_DOCTOR_INFO_SUCCESS: "CREATE_DOCTOR_INFO_SUCCESS",
  CREATE_DOCTOR_INFO_FAILED: "CREATE_DOCTOR_INFO_FAILED",

  GET_DETAIL_INFO_DOCTOR_SUCCESS: "GET_DETAIL_INFO_DOCTOR_SUCCESS",
  GET_DETAIL_INFO_DOCTOR_FAILED: "GET_DETAIL_INFO_DOCTOR_FAILED",

  GET_CONTENT_MARKDOWN_SUCCESS: "GET_CONTENT_MARKDOWN_SUCCESS",
  GET_CONTENT_MARKDOWN_FAILED: "GET_DETAIL_INFO_DOCTOR_FAILED",

  UPDATE_CONTENT_MARKDOWN_SUCCESS: "UPDATE_CONTENT_MARKDOWN_SUCCESS",
  UPDATE_CONTENT_MARKDOWN_FAILED: "UPDATE_DETAIL_INFO_DOCTOR_FAILED",

  GET_SCHEDULE_TIMES_SUCCESS: "GET_SCHEDULE_TIMES_SUCCESS",
  GET_SCHEDULE_TIMES_FAILED: "GET_SCHEDULE_TIMES_FAILED",

  CREATE_SCHEDULES_SUCCESS: "CREATE_SCHEDULES_SUCCESS",
  CREATE_SCHEDULES_FAILED: "CREATE_SCHEDULES_FAILED",

  GET_SCHEDULE_BY_DATE_SUCCESS: "GET_SCHEDULE_BY_DATE_SUCCESS",
  GET_SCHEDULE_BY_DATE_FAILED: "GET_SCHEDULE_BY_DATE_FAILED",
});

export default actionTypes;
